Dev
GIS-sys/Android-Mipt-Project-2024-Egorov pull request #2
Opened 2024-03-21 18:23 UTC by GIS-sys

2024-03-28 09:41 UTC, GIS-sys commented
Добавил ридми в ветку dev

2024-03-31 08:34 UTC, Ksalim01 commented
1. В описание сказано, что нужно дать пермишен на гео, но я не вижу никакого попапа с пермишеном.
2. После нажатия на кнопку старт появляется белый экран. Поводил телефоном по небу, ничего не увидел.
UI первого экрана очень скудный, одна кнопка и текст. Хочется поправить паддинги, размер текста, цвета и тп. 
Первое - критичное, т.к. приложение фактически не работает, второе - опциональное (влияет на доп баллы)

2024-03-31 09:31 UTC, Ksalim01 commented
https://github.com/GIS-sys/Android-Mipt-Project-2024-Egorov/assets/60807855/2f3627a6-a845-492b-b726-357d824c081a

Экран настроек как-то не работает.
Плюс луна как-то не двигается на экране. Просто вижу статичную картинку, в центре которой недвигающийся овал)

2024-03-31 11:49 UTC, Ksalim01 requested changes

2024-03-31 11:49 UTC, Ksalim01 commented on app/src/main/java/com/giswarm/mipt_2024/IntentProcessor.kt
> +                "main.text" -> {
лучше вынести в статические переменные

2024-03-31 11:49 UTC, Ksalim01 commented on app/src/main/java/com/giswarm/mipt_2024/position/DevicePosition.kt
> +    }
Давай поступим так. Т.к. на данный момент активити является неким централизованным объектом, то все нужные зависимости хранить там и если надо, получать эти зависимости во фрагментах через это активити. Для этого, например, можно сделать интерфейсы DevicePositionManagerProvider, GpsPositionProvider и тп. Эти интерфейсы имплементишь в активити, а во фрагментах достаешь нужный интерфейс и работаешь с ним.

2024-03-31 11:49 UTC, Ksalim01 commented on app/src/main/java/com/giswarm/mipt_2024/fragment/GreetingsFragment.kt
> +        if (requireActivity().getSharedPreferences("PREFERENCE_NAME",  Context.MODE_PRIVATE).getBoolean(PREFERENCES_ALREADY_SHOWN, false)) {
Тоже вынести в константу

2024-03-31 11:49 UTC, Ksalim01 commented on app/src/main/java/com/giswarm/mipt_2024/fragment/CredentialsFragment.kt
>      }
можно не добавлять, раз уж ничего нет)

2024-03-31 11:49 UTC, Ksalim01 commented on app/src/main/java/com/giswarm/mipt_2024/fragment/GreetingsFragment.kt
> +        parentFragmentManager.commit {
parentFragmentManager не рекомендуется к использованию. Используй childFragmentManager

2024-03-31 11:49 UTC, Ksalim01 commented on app/src/main/java/com/giswarm/mipt_2024/fragment/MainFragment.kt
> +        parentFragmentManager.commit {
childFragmentManager

2024-03-31 11:49 UTC, Ksalim01 commented on app/src/main/java/com/giswarm/mipt_2024/IntentProcessor.kt
> +                    actionsTransitionsList.add("settings")
По какому принципу тут ставится префикс main? Вроде в credentials и в settings тоже добавляешь в свой список

2024-03-31 11:49 UTC, Ksalim01 commented on app/src/main/java/com/giswarm/mipt_2024/fragment/GreetingsFragment.kt
> +        private const val PREFERENCES_ALREADY_SHOWN = "GREETINGS_ALREADY_SHOWN"
Необязательно заворачивать в companion object. Можно просто поместить это выше твоего класса

2024-03-31 11:49 UTC, Ksalim01 commented on app/src/main/java/com/giswarm/mipt_2024/fragment/MainFragment.kt
> +    private var fragmentIndex: Long = -1
Это нужно только для диплинков?

2024-03-31 11:49 UTC, Ksalim01 commented on app/src/main/java/com/giswarm/mipt_2024/fragment/MainFragment.kt
> +                    IntentProcessor.actionsTransitionsList.removeAt(0)
removeFirst

2024-03-31 11:49 UTC, Ksalim01 commented on app/src/main/java/com/giswarm/mipt_2024/fragment/MainFragment.kt
> +                    IntentProcessor.actionsTransitionsList.removeAt(0)
за O(N) работает, не очень хорошо

2024-03-31 11:49 UTC, Ksalim01 commented on app/src/main/java/com/giswarm/mipt_2024/fragment/GreetingsFragment.kt
> +        requireActivity().getSharedPreferences("PREFERENCE_NAME",  Context.MODE_PRIVATE).edit().putBoolean(PREFERENCES_ALREADY_SHOWN, true).commit()
вместо commit лучше сделать apply

2024-04-03 15:49 UTC, GIS-sys commented on app/src/main/java/com/giswarm/mipt_2024/fragment/GreetingsFragment.kt
> +        requireActivity().getSharedPreferences("PREFERENCE_NAME",  Context.MODE_PRIVATE).edit().putBoolean(PREFERENCES_ALREADY_SHOWN, true).commit()
Тут ведь я хочу точно убедиться, что больше этот экран показываться не будет, поэтому я сразу убеждаюсь, что переменная записана (вдруг телефон выключится или ещё что-то такое случится, и данные сбросятся)

Но сделал apply, всё равно разница минимальная в данном конкретном случае

2024-04-03 15:54 UTC, GIS-sys commented on app/src/main/java/com/giswarm/mipt_2024/fragment/MainFragment.kt
> +    private var fragmentIndex: Long = -1
fragmentIndex? Нет, это с диплинками не связано. Это нужно для того, чтобы выбирать, какой внутренний fragment (внутри MainFragment) показывать - TextView или VisualView. В задании был такой пункт - сделать, чтобы в основном фрагменте был внутренний

2024-04-03 15:58 UTC, GIS-sys commented on app/src/main/java/com/giswarm/mipt_2024/IntentProcessor.kt
> +                    actionsTransitionsList.add("settings")
settings, main, credentials - это всё самостоятельные фрагменты
А visual и text -  это фрагменты внутри фрагмента main. Поэтому main.visual и main.text, но просто settings и credentials

А в actionsTransitionsList добавляется список-последовательность экранов, которая говорит, как нужно пройти по экранам, чтобы добраться до нужного. Пример: если мы хотим открыть диплинком settings, то если просто сразу поставить фрагмент settings - при нажатии на кнопку Назад мы выйдем из приложения. А я сделал так, что мы прошли полностью путь main-settings, поэтому при нажатии Назад мы просто перейдём в Main и будем там работать. Ну и в целом приложение может рассчитывать на то, что всё честно, корректно восстанавливается, не телепортируясь магически

2024-04-03 16:11 UTC, GIS-sys commented on app/src/main/java/com/giswarm/mipt_2024/fragment/GreetingsFragment.kt
> +        parentFragmentManager.commit {
Но мне нужно изнутри фрагмента сказать родителю, чтобы он заменил текущий фрагмент на другой. То есть, я вот нахожусь в GreetingsFragment, и я хочу перейти в MainFragment. Кто-то ведь должен сказать  fragmentManager-у чтобы он сменил фрагмент?

Переделал так, что теперь фрагменты просят Activity поменять фрагмент вместо них. Не знаю, лучше ли этот способ, но ничего другого не придумал

2024-04-03 16:45 UTC, GIS-sys commented on app/src/main/java/com/giswarm/mipt_2024/position/DevicePosition.kt
> +    }
Переместил, хотя мне кажется, что код стал более... скомканным, наверное. Ну да ладно

2024-04-03 16:47 UTC, GIS-sys commented
> video_2024-03-31_12-30-07.mp4
> 
> Экран настроек как-то не работает. Плюс луна как-то не двигается на экране. Просто вижу статичную картинку, в центре которой недвигающийся овал) Еще видно, что текст обрезается в "Показывать луну как"

Пока (на первом этапе проекта) функционал не реализовывался, будет на следующих этапах. UI подвигаю, посмотрю, как сделать, чтобы не обрезался

2024-04-03 17:28 UTC, GIS-sys commented on app/src/main/java/com/giswarm/mipt_2024/fragment/MainFragment.kt
> +                    IntentProcessor.actionsTransitionsList.removeAt(0)
заменил на дек

2024-04-03 18:08 UTC, GIS-sys commented
UI постарался поправить, заменил расположение кнопок на MainFragment, и в SettingsFragment поменял расположение выпадающего списка

2024-04-13 12:58 UTC, Ksalim01 commented on app/src/main/java/com/giswarm/mipt_2024/position/DevicePosition.kt
> +    }
Ну в следующих этапах будет DI, через него и будешь получать нужные зависимости. По крайней мере будет проще переходить на нормальный DI используя схему, которую предложил я.

2024-04-13 13:14 UTC, Ksalim01 commented
Пройдусь по пунктам из тз и сразу выставлю баллы
1. (4) в целом ок 
2. (0.5) ок
3. (0.5) увидел использование квалификаторов, в темной и светлой теме есть отличия
4. (0.5) ок
5. (0.5) очень простенько
6. (1) состояние сохраняется в настройках и немного на гланом экране (ок с индексом, не ок с урлом)
7. (2) ок 
8. (0.5) ок
9. Добавь лектора в ревью)

2024-04-13 13:14 UTC, Ksalim01 reviewed
Добавь лектора

2024-04-13 13:53 UTC, GIS-sys commented
> Добавь лектора

Я бы добавил, если бы лектор принял приглашение в коллабораторы :(

2024-04-13 14:43 UTC, Ksalim01 commented
> > Добавь лектора
> 
> Я бы добавил, если бы лектор принял приглашение в коллабораторы :(

Напиши ему в лс

2024-04-16 11:17 UTC, merged

2024-04-19 11:09 UTC, DzhangirliEmil commented on app/src/main/java/com/giswarm/mipt_2024/fragment/GreetingsFragment.kt
> +        parentFragmentManager.commit {
Каждый фрагмент должен запрашивать внешние зависимости, в том числе навигационный. И родительский фрагмент/активити должы эти зависимости реализовывать